// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gin "github.com/gin-gonic/gin"
import mock "github.com/stretchr/testify/mock"

// RegisterController is an autogenerated mock type for the RegisterController type
type RegisterController struct {
	mock.Mock
}

// PostRegister provides a mock function with given fields: ginContext
func (_m *RegisterController) PostRegister(ginContext *gin.Context) {
	_m.Called(ginContext)
}
